# Generated by Django 4.1 on 2023-01-31 05:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_alter_image_aspect_ratio"),
        ("lists", "0003_alter_list_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="list",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="lists", to="images.image"
            ),
        ),
    ]
