# Generated by Django 4.1 on 2023-02-01 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_alter_image_aspect_ratio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lists", "0004_alter_list_description_alter_list_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="image_lists", to="images.image"
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
