"""
Django settings for nekosapi project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import string
import secrets

import dotenv

dotenv.load_dotenv()

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "API_SECRET_KEY",
    "".join([secrets.choice(string.ascii_letters + string.digits) for _ in range(50)]),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("API_DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = os.getenv("API_ALLOWED_HOSTS", "127.0.0.1 localhost").split(" ")
CSRF_TRUSTED_ORIGINS = [
    f"https://{host}" for host in os.getenv("API_ALLOWED_HOSTS", "127.0.0.1 localhost").split(" ")
] + [
    f"http://{host}" for host in os.getenv("API_ALLOWED_HOSTS", "127.0.0.1 localhost").split(" ")
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "nekosapi.images.apps.ImagesConfig",
    "nekosapi.artists.apps.ArtistsConfig",
    "nekosapi.characters.apps.CharactersConfig",
    "django_cleanup.apps.CleanupConfig",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "nekosapi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "nekosapi.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DATABASE_NAME", "nekosapi"),
        "USER": os.getenv("DATABASE_USER", "nekosapi"),
        "PASSWORD": os.getenv("DATABASE_PASS", "nekosapi"),
        "HOST": os.getenv("DATABASE_HOST", "database"),
        "PORT": os.getenv("DATABASE_PORT", "5432"),
    }
}

STORAGES = {
    "default": {
        "BACKEND": "django_bunny.storage.BunnyStorage",
    },
    "staticfiles": {
        "BACKEND": "django_bunny.storage.BunnyStorage",
        "base_dir": "static/",
    },
}

BUNNY_USERNAME = os.getenv("BUNNY_USERNAME", "nekosapi")
BUNNY_PASSWORD = os.getenv("BUNNY_PASSWORD", "nekosapi")
BUNNY_REGION = os.getenv("BUNNY_REGION", "la")
BUNNY_HOSTNAME = os.getenv("BUNNY_HOSTNAME", "https://b-cdn.net")

NINJA_DOCS_VIEW = os.getenv("API_DOCS_VIEW", "redoc").lower()

CORS_ALLOW_ALL_ORIGINS = os.getenv("API_CORS_ALLOW_ALL_ORIGINS", "true").lower() == "true"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "https://cdn.nekosapi.com/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
