# Generated by Django 4.1.5 on 2023-03-31 14:00

from django.db import migrations
import django_resized.forms
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0004_alter_application_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="icon",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[1024, 1024],
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="uploads/applications/icons/{uuid:base32}{ext}"
                ),
            ),
        ),
    ]
