# Generated by Django 4.2.3 on 2023-07-24 21:41

from django.db import migrations
import django_resized.forms
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0006_application_post_logout_redirect_uris"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="icon",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[1024, 1024],
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="applications/icons/{uuid:base32}{ext}"
                ),
            ),
        ),
    ]
