# Generated by Django 4.1.5 on 2023-01-29 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_alter_image_aspect_ratio"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_images",
            field=models.ManyToManyField(blank=True, to="images.image"),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=500,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
