# Generated by Django 4.1 on 2023-01-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_alter_image_aspect_ratio"),
        ("users", "0006_user_followed_artists_user_followed_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_images",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by", to="images.image"
            ),
        ),
    ]
