# Generated by Django 4.1 on 2023-01-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_list_created_at_list_updated_at"),
        ("users", "0007_user_saved_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followed_lists",
            field=models.ManyToManyField(related_name="followers", to="lists.list"),
        ),
    ]
