# Generated by Django 4.1.5 on 2023-02-04 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_avatar_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
