# Generated by Django 4.1.5 on 2023-02-05 05:09

from django.db import migrations, models
import django_resized.forms
import dynamic_filenames


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_discorduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="access_token",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discorduser",
            name="refresh_token",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                force_format="WEBP",
                keep_meta=True,
                quality=100,
                scale=1,
                size=[512, 512],
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="uploads/user/avatar/{uuid:base32}{ext}"
                ),
            ),
        ),
    ]
