# Generated by Django 4.1.5 on 2023-02-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_discorduser_access_token_discorduser_refresh_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biography",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
