# Generated by Django 4.1.5 on 2023-01-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="is_nsfw",
            field=models.BooleanField(
                default=False,
                help_text="Wether the name or description of the category contain NSFW content or not.",
                verbose_name="Is NSFW",
            ),
        ),
    ]
