# Generated by Django 4.1.5 on 2023-01-26 04:22

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The artist's name", max_length=50),
                ),
                (
                    "aliases",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        help_text="Other names the artist is known as.",
                        size=None,
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        help_text="The artist's avatar/profile picture.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "links",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=256),
                        help_text="Links to the artist's social media, website, pixiv, etc.",
                        size=None,
                    ),
                ),
            ],
        ),
    ]
