# Generated by Django 4.2 on 2023-05-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gif",
            old_name="chaarcters",
            new_name="characters",
        ),
        migrations.AlterField(
            model_name="gif",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
