# Generated by Django 4.2 on 2023-05-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_options_alter_category_is_nsfw"),
        ("characters", "0004_alter_character_gender"),
        ("gifs", "0002_rename_chaarcters_gif_characters_alter_gif_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gif",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="gifs", to="categories.category"
            ),
        ),
        migrations.AlterField(
            model_name="gif",
            name="characters",
            field=models.ManyToManyField(
                blank=True, related_name="gifs", to="characters.character"
            ),
        ),
    ]
