# Generated by Django 4.2 on 2023-05-09 14:52

from django.db import migrations
import dynamic_filenames
import thumbnails.fields


class Migration(migrations.Migration):
    dependencies = [
        ("gifs", "0003_alter_gif_categories_alter_gif_characters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gif",
            name="file",
            field=thumbnails.fields.ImageField(
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="uploads/gifs/{uuid:base32}{ext}"
                )
            ),
        ),
    ]
