# Generated by Django 4.2 on 2023-05-29 03:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifs", "0007_reaction_is_nsfw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gif",
            name="emotions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("sadness", "Sadness"),
                        ("happiness", "Happiness"),
                        ("fear", "Fear"),
                        ("anger", "Anger"),
                        ("surprise", "Surprise"),
                        ("disgust", "Disgust"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=[],
                help_text="Sadness, Happiness, Fear, Anger, Surprise, Disgust",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="name",
            field=models.CharField(
                help_text="Keep it neutral (?). For example, <b>Wave</b> but not <b>Waving</b>.",
                max_length=100,
                unique=True,
            ),
        ),
    ]
