# Generated by Django 4.2 on 2023-05-29 03:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifs", "0008_alter_gif_emotions_alter_reaction_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gif",
            name="emotions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("sadness", "Sadness"),
                        ("happiness", "Happiness"),
                        ("fear", "Fear"),
                        ("anger", "Anger"),
                        ("surprise", "Surprise"),
                        ("disgust", "Disgust"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                help_text="Sadness, Happiness, Fear, Anger, Surprise, Disgust",
                size=None,
            ),
        ),
    ]
