# Generated by Django 4.2 on 2023-06-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifs", "0009_alter_gif_emotions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gif",
            name="reactions",
            field=models.ManyToManyField(
                blank=True, related_name="gifs", to="gifs.reaction"
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Keep it neutral (?). For example, <b>Wave</b> but not <b>Waving</b>.",
                max_length=100,
                unique=True,
            ),
        ),
    ]
