# Generated by Django 4.2 on 2023-06-04 02:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifs", "0010_alter_gif_reactions_alter_reaction_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gif",
            name="age_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sfw", "Sfw"),
                    ("questionable", "Questionable"),
                    ("suggestive", "Suggestive"),
                    ("borderline", "Borderline"),
                    ("explicit", "Explicit"),
                ],
                db_index=True,
                help_text="The image's sfw-ness.",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gif",
            name="emotions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("sadness", "Sadness"),
                        ("happiness", "Happiness"),
                        ("fear", "Fear"),
                        ("anger", "Anger"),
                        ("surprise", "Surprise"),
                        ("disgust", "Disgust"),
                    ],
                    max_length=30,
                ),
                blank=True,
                db_index=True,
                default=list,
                help_text="Sadness, Happiness, Fear, Anger, Surprise, Disgust",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="gif",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_reviewed", "Not Reviewed"),
                    ("on_review", "On Review"),
                    ("declined", "Declined"),
                    ("verified", "Verified"),
                ],
                db_index=True,
                default="not_reviewed",
                help_text="The image's verification status.",
                max_length=12,
            ),
        ),
    ]
