# Generated by Django 4.2.3 on 2023-08-01 01:19

from django.db import migrations, models
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("gifs", "0011_alter_gif_age_rating_alter_gif_emotions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gif",
            name="file",
            field=models.FileField(
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="gifs/{uuid:base32}{ext}"
                )
            ),
        ),
    ]
