# Generated by Django 4.1.5 on 2023-01-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_options_alter_category_is_nsfw"),
        ("images", "0002_image_characters_image_created_at_image_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="categories",
            field=models.ManyToManyField(
                related_name="images", to="categories.category"
            ),
        ),
    ]
