# Generated by Django 4.1.5 on 2023-01-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_alter_image_age_rating_alter_image_artist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="aspect_ratio",
            field=models.CharField(
                blank=True,
                help_text="The image's aspect ratio (w:h).",
                max_length=11,
                null=True,
            ),
        ),
    ]
