# Generated by Django 4.1.5 on 2023-02-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0011_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
