# Generated by Django 4.1.5 on 2023-01-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_alter_image_aspect_ratio"),
        ("users", "0004_user_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="favorite_images",
        ),
        migrations.AddField(
            model_name="user",
            name="liked_images",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to="images.image"
            ),
        ),
    ]
