# Generated by Django 4.1.5 on 2023-02-02 19:27

from django.db import migrations
import django_resized.forms
import dynamic_filenames


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_followed_lists"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                default="",
                force_format="WEBP",
                keep_meta=True,
                quality=100,
                scale=1,
                size=[400, 400],
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="uploads/user/avatar/{uuid:base32}{ext}"
                ),
            ),
            preserve_default=False,
        ),
    ]
