# Generated by Django 4.1.5 on 2023-02-11 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_biography_user_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleUser",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("access_token", models.CharField(max_length=256)),
                ("refresh_token", models.CharField(max_length=256)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
