# Generated by Django 4.1.5 on 2023-02-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_googleuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="googleuser",
            name="id",
            field=models.BigIntegerField(
                default=0, primary_key=True, serialize=False, unique=True
            ),
            preserve_default=False,
        ),
    ]
