# Generated by Django 4.1.5 on 2023-02-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_googleuser_id_alter_googleuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleuser",
            name="id",
            field=models.CharField(
                max_length=256, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
