# Generated by Django 4.1.5 on 2023-02-11 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_googleuser_access_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubUser",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub User",
                "verbose_name_plural": "GitHub Users",
            },
        ),
    ]
