# Generated by Django 4.1.5 on 2023-03-31 14:00

from django.db import migrations
import django_resized.forms
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_alter_user_avatar_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[512, 512],
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="uploads/user/avatar/{uuid:base32}{ext}"
                ),
            ),
        ),
    ]
