# Generated by Django 4.1.5 on 2023-04-16 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_alter_user_avatar_image"),
    ]

    operations = [

    ]
