# Generated by Django 4.1.5 on 2023-04-16 05:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(
                max_length=253,
                unique=True,
                validators=[users.models.Domain.validate_domain],
            ),
        ),
    ]
