# Generated by Django 4.1.5 on 2023-04-16 06:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_domain_name"),
    ]

    operations = [

    ]
