# Generated by Django 4.1.5 on 2023-04-16 06:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_domain_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="verification_method",
            field=models.CharField(
                choices=[("dns", "Dns"), ("file", "File")], default="dns", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="verification_token",
            field=models.CharField(
                default=users.models.Domain.generate_token,
                editable=False,
                max_length=43,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(
                max_length=254,
                unique=True,
                validators=[users.models.Domain.validate_domain],
            ),
        ),
    ]
