# Generated by Django 4.1.5 on 2023-04-16 18:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_domain_verification_method_domain_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="secret_key",
            field=models.CharField(
                default=users.models.User.generate_secret_key, max_length=256
            ),
        ),
    ]
