# Generated by Django 4.2.1 on 2023-07-24 03:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_user_secret_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 32 characters or fewer. Lowercase letters, digits and /./_ only.",
                max_length=32,
                unique=True,
                validators=[users.models.User.username_validator],
                verbose_name="username",
            ),
        ),
    ]
