# Generated by Django 4.2.6 on 2023-10-22 05:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("images", "0003_image_artist_alter_image_image_alter_image_sample_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="The character's complete name. Last name first, followed by a comma, followed by the first name."
                    ),
                ),
                (
                    "aliases",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        help_text="Other names the character is officially known as.",
                        size=None,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A brief description of the character.", null=True
                    ),
                ),
                (
                    "ages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(),
                        blank=True,
                        help_text="All the ages the character offically has/has officially had.",
                        size=None,
                    ),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(
                        help_text="The character's height in cm.", null=True
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        help_text="The character's weight in kg.", null=True
                    ),
                ),
                (
                    "gender",
                    models.TextField(help_text="The character's gender.", null=True),
                ),
                (
                    "species",
                    models.TextField(
                        default="Human", help_text="The character's species.", null=True
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        help_text="The character's birthday. Year doesn't matter.",
                        null=True,
                    ),
                ),
                (
                    "nationality",
                    models.TextField(
                        help_text="The character's nationality.", null=True
                    ),
                ),
                (
                    "occupations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        help_text="All the occupations the character officially has/has officially had.",
                        size=None,
                    ),
                ),
                (
                    "main_image",
                    models.ForeignKey(
                        help_text="An image that illustrates the character. Something like what you'd see as the image for a character in MAL or AniList.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="images.image",
                    ),
                ),
            ],
        ),
    ]
