# Generated by Django 4.2.6 on 2023-10-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="policy_credit",
            field=models.BooleanField(default=True),
        ),
    ]
