# Generated by Django 4.2.6 on 2023-10-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0001_initial"),
        ("images", "0003_image_artist_alter_image_image_alter_image_sample_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="characters",
            field=models.ManyToManyField(
                blank=True, related_name="images", to="characters.character"
            ),
        ),
    ]
