# Generated by Django 4.2.6 on 2023-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0005_alter_image_hash_md5"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="id_v2",
            field=models.UUIDField(null=True, verbose_name="ID v2"),
        ),
        migrations.AddField(
            model_name="image",
            name="image_v2",
            field=models.URLField(null=True, verbose_name="Image URL v2"),
        ),
    ]
