# Generated by Django 4.2.6 on 2023-10-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_id_v2_image_image_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rating',
            field=models.CharField(choices=[('safe', 'Safe'), ('suggestive', 'Suggestive'), ('borderline', 'Borderline'), ('explicit', 'Explicit')], max_length=12, null=True),
        ),
    ]
