# Generated by Django 4.2.6 on 2023-10-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_alter_image_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='id_v2',
            field=models.UUIDField(null=True),
        ),
    ]
