# Generated by Django 4.2.6 on 2023-10-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_tag_id_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='sub',
            field=models.CharField(choices=[('format', 'Format'), ('character', 'Character'), ('setting', 'Setting')], default='format', max_length=9),
        ),
    ]
