# Generated by Django 4.2.6 on 2023-11-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_tag_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_v2',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL v2'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id_v2',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
