# Generated by Django 4.2.6 on 2024-02-25 19:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_alter_image_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='danbooru_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_index=True, default=list, size=None),
        ),
    ]
