# Generated by Django 4.2.6 on 2024-02-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_artist_id_v2'),
        ('images', '0014_alter_tag_danbooru_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artists.artist'),
        ),
    ]
