# Generated by Django 4.2 on 2023-06-04 02:27

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_options_alter_category_is_nsfw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_nsfw",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Wether the name or description of the category contain NSFW content or not.",
                verbose_name="Is NSFW",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                models.OrderBy(
                    django.db.models.functions.text.Lower("type"), descending=True
                ),
                name="category_type_index",
            ),
        ),
    ]
