# Generated by Django 4.2.6 on 2023-10-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='id_v2',
            field=models.UUIDField(null=True),
        ),
    ]
