# Generated by Django 4.2.6 on 2024-01-19 06:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_id_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='danbooru_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_index=True, default=[], size=None),
        ),
    ]
