# Generated by Django 4.2.6 on 2024-01-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_alter_image_rating'),
        ('characters', '0004_character_danbooru_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='birthday',
            field=models.DateField(blank=True, help_text="The character's birthday. Year doesn't matter.", null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, help_text="The character's height in cm.", null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text="An image that illustrates the character. Something like what you'd see as the image for a character in MAL or AniList.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, help_text="The character's weight in kg.", null=True),
        ),
    ]
