# Generated by Django 4.2.6 on 2024-02-25 19:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_character_birthday_alter_character_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='main_image',
        ),
        migrations.AlterField(
            model_name='character',
            name='danbooru_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_index=True, default=list, size=None),
        ),
    ]
