# Generated by Django 4.1.5 on 2023-04-16 05:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "events",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("on-image-create", "On Image Create"),
                                ("on-image-update", "On Image Update"),
                                ("on-image-delete", "On Image Delete"),
                                ("on-artist-create", "On Artist Create"),
                                ("on-artist-update", "On Artist Update"),
                                ("on-artist-delete", "On Artist Delete"),
                            ],
                            max_length=16,
                        ),
                        size=None,
                    ),
                ),
                (
                    "urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), size=None
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
