# Generated by Django 4.1.5 on 2023-04-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="urls",
            field=models.CharField(max_length=256),
        ),
    ]
