# Generated by Django 4.1.5 on 2023-04-24 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0002_alter_webhook_urls"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webhook",
            old_name="urls",
            new_name="url",
        ),
    ]
