# Generated by Django 4.2 on 2023-04-25 04:28

import django.contrib.postgres.fields
from django.db import migrations, models
import webhooks.models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0003_rename_urls_webhook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="verification_key",
            field=models.CharField(
                default=webhooks.models.Webhook.generate_token, max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="events",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("on-image-create", "On Image Create"),
                        ("on-image-update", "On Image Update"),
                        ("on-image-delete", "On Image Delete"),
                        ("on-artist-create", "On Artist Create"),
                        ("on-artist-update", "On Artist Update"),
                        ("on-artist-delete", "On Artist Delete"),
                        ("on-category-create", "On Category Create"),
                        ("on-category-update", "On Category Update"),
                        ("on-category-delete", "On Category Delete"),
                        ("on-character-create", "On Character Create"),
                        ("on-character-update", "On Character Update"),
                        ("on-character-delete", "On Character Delete"),
                    ],
                    max_length=19,
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="url",
            field=models.CharField(
                max_length=256, validators=[webhooks.models.Webhook.validate_url]
            ),
        ),
    ]
