# Generated by Django 4.1.5 on 2023-01-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="species",
            field=models.CharField(default="Human", max_length=20, null=True),
        ),
    ]
