# Generated by Django 4.1.5 on 2023-01-27 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_character_species"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="birth_date",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="nationality",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
