# Generated by Django 4.2.6 on 2023-10-21 19:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        height_field="image_height",
                        null=True,
                        upload_to="",
                        width_field="image_width",
                    ),
                ),
                (
                    "sample",
                    models.ImageField(
                        blank=True,
                        height_field="sample_height",
                        null=True,
                        upload_to="",
                        width_field="sample_width",
                    ),
                ),
                ("image_size", models.PositiveIntegerField(blank=True, null=True)),
                ("image_width", models.PositiveIntegerField(blank=True, null=True)),
                ("image_height", models.PositiveIntegerField(blank=True, null=True)),
                ("sample_size", models.PositiveIntegerField(blank=True, null=True)),
                ("sample_width", models.PositiveIntegerField(blank=True, null=True)),
                ("sample_height", models.PositiveIntegerField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "verification",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("on_review", "On review"),
                            ("declined", "Declined"),
                            ("unverified", "Unverified"),
                        ],
                        default="unverified",
                        max_length=10,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("safe", "Safe"),
                            ("questionable", "Questionable"),
                            ("borderline", "Borderline"),
                            ("explicit", "Explicit"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                ("hash_md5", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "hash_perceptual",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "color_dominant",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(), null=True, size=3
                    ),
                ),
                (
                    "color_palette",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.PositiveSmallIntegerField(), size=3
                        ),
                        null=True,
                        size=10,
                    ),
                ),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("is_original", models.BooleanField(default=False)),
                ("is_screenshot", models.BooleanField(default=False)),
                ("is_flagged", models.BooleanField(default=False)),
                ("is_animated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
