# Generated by Django 4.2.6 on 2023-10-22 00:35

from django.db import migrations, models
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_nsfw", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="image",
            name="hash_md5",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="hash_perceptual",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="/images/original/{uuid}{ext}"
                ),
                width_field="image_width",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_height",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_size",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_width",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="rating",
            field=models.CharField(
                choices=[
                    ("safe", "Safe"),
                    ("questionable", "Questionable"),
                    ("borderline", "Borderline"),
                    ("explicit", "Explicit"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="sample",
            field=models.ImageField(
                blank=True,
                height_field="sample_height",
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="/images/360/{uuid}{ext}"
                ),
                width_field="sample_width",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="sample_height",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="sample_size",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="sample_width",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="source",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="source_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(blank=True, to="images.tag"),
        ),
    ]
