# Generated by Django 4.2.6 on 2023-10-22 03:55

from django.db import migrations, models
import django.db.models.deletion
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0001_initial"),
        (
            "images",
            "0002_tag_alter_image_hash_md5_alter_image_hash_perceptual_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="artists.artist",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="images/original/{uuid}{ext}"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="sample",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="images/360/{uuid}{ext}"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="images", to="images.tag"
            ),
        ),
    ]
