# Generated by Django 4.2.6 on 2023-10-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0004_image_characters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="hash_md5",
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
