# Generated by Django 4.1.5 on 2023-01-26 02:46

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50, null=True)),
                (
                    "aliases",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        size=None,
                    ),
                ),
                ("description", models.CharField(max_length=512, null=True)),
                ("gender", models.CharField(max_length=20, null=True)),
                (
                    "ages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SmallIntegerField(), blank=True, size=None
                    ),
                ),
                ("birth_date", models.CharField(max_length=14, null=True)),
                ("nationality", models.CharField(max_length=20, null=True)),
                (
                    "occupations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
