# Generated by Django 4.1.5 on 2023-01-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_alter_character_birth_date_alter_character_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
