# Generated by Django 4.1 on 2023-01-31 05:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_list_created_at_list_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=50, primary_key=True, serialize=False
            ),
        ),
    ]
