# Generated by Django 4.2.6 on 2023-10-22 03:55

import django.contrib.postgres.fields
from django.db import migrations, models
import dynamic_filenames


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="artists/original/{filename}{ext}"
                        ),
                    ),
                ),
                (
                    "aliases",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, size=None
                    ),
                ),
                (
                    "links",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(), size=None
                    ),
                ),
                ("policy_repost", models.BooleanField(null=True)),
                ("policy_credit", models.BooleanField(null=True)),
                ("policy_ai", models.BooleanField(default=False)),
            ],
        ),
    ]
