# Generated by Django 4.2.6 on 2023-11-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_id_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id_v2',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
