# Generated by Django 4.1.5 on 2023-01-26 23:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="image",
            field=models.URLField(
                blank=True,
                help_text="The artist's avatar/profile picture.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="links",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=256),
                blank=True,
                help_text="Links to the artist's social media, website, pixiv, etc.",
                size=None,
            ),
        ),
    ]
