# Generated by Django 4.1.5 on 2023-02-10 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_alter_artist_image_alter_artist_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
