# Generated by Django 4.2 on 2023-06-04 02:27

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0003_artist_created_at_artist_updated_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(
                models.OrderBy(
                    django.db.models.functions.text.Lower("name"), descending=True
                ),
                name="artist_name_index",
            ),
        ),
    ]
