# Generated by Django 4.2.1 on 2023-06-05 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_sharedresourcetoken_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedresourcetoken",
            name="object_id",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="sharedresourcetoken",
            name="token",
            field=models.CharField(
                db_index=True,
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_token",
                        message="Token must be 20 characters long and URL safe.",
                        regex="^[\\w-]{20}$",
                    )
                ],
            ),
        ),
    ]
