# Generated by Django 4.1.5 on 2023-01-25 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("height", models.SmallIntegerField(default=0)),
                ("width", models.SmallIntegerField(default=0)),
                ("aspect_ratio", models.CharField(max_length=11)),
                ("source_url", models.URLField(null=True)),
                ("source_name", models.CharField(max_length=20, null=True)),
                (
                    "age_rating",
                    models.CharField(
                        choices=[
                            ("sfw", "Sfw"),
                            ("questionable", "Questionable"),
                            ("borderline", "Borderline"),
                            ("explicit", "Explicit"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                ("is_original", models.BooleanField(default=False)),
            ],
        ),
    ]
