# Generated by Django 4.1.5 on 2023-01-26 05:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_image_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="dominant_color",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SmallIntegerField(), null=True, size=3
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="primary_color",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SmallIntegerField(), null=True, size=3
            ),
        ),
    ]
