# Generated by Django 4.1.5 on 2023-02-02 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("images", "0008_image_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="uploader",
            field=models.ForeignKey(
                default="8fad93cd-4a9c-4e71-b21f-6eb4efebb3db",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posted_images",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
