# Generated by Django 4.1.5 on 2023-02-20 07:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0013_remove_image_is_verified_image_verification_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="age_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sfw", "Sfw"),
                    ("questionable", "Questionable"),
                    ("suggestive", "Suggestive"),
                    ("borderline", "Borderline"),
                    ("explicit", "Explicit"),
                ],
                help_text="The image's sfw-ness.",
                max_length=12,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ImageSourceResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("result", models.JSONField(max_length=10000)),
                (
                    "source",
                    models.CharField(
                        choices=[("SauceNAO", "Sauce Nao"), ("IQDB", "Iqdb")],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_queries",
                        to="images.image",
                    ),
                ),
            ],
        ),
    ]
