# Generated by Django 4.1.5 on 2023-02-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0014_alter_image_age_rating_imagesourceresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagesourceresult",
            name="status",
            field=models.SmallIntegerField(default=400),
        ),
    ]
