# Generated by Django 4.1.5 on 2023-03-31 14:00

from django.db import migrations, models
import django_resized.forms
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0016_remove_imagesourceresult_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="aspect_ratio",
            field=models.CharField(
                blank=True,
                help_text="The image's aspect ratio (w:h).",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=100,
                scale=None,
                size=None,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="uploads/images/{uuid:base32}{ext}"
                ),
            ),
        ),
    ]
