# Generated by Django 4.1.5 on 2023-03-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0017_alter_image_aspect_ratio_alter_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("landscape", "Landscape"),
                    ("portrait", "Portrait"),
                    ("square", "Square"),
                ],
                max_length=9,
                null=True,
            ),
        ),
    ]
