# Generated by Django 4.1.5 on 2023-03-31 22:53

import django.contrib.postgres.fields
from django.db import migrations, models
import images.models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0018_image_orientation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="primary_color",
        ),
        migrations.AddField(
            model_name="image",
            name="palette",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.SmallIntegerField(),
                    size=3,
                    validators=[images.models.Image.validate_rgb_value],
                ),
                blank=True,
                null=True,
                size=10,
            ),
        ),
    ]
