# Generated by Django 4.1.5 on 2023-04-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0020_image_mimetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The file size in bytes of the image file.",
                null=True,
            ),
        ),
    ]
