# Generated by Django 4.2 on 2023-05-10 02:33

from django.db import migrations
import django_resized.forms
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0021_image_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=100,
                scale=None,
                size=None,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="images/{uuid:base32}{ext}"
                ),
            ),
        ),
    ]
