# Generated by Django 4.2.3 on 2023-07-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0022_alter_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="hash_perceptual",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Perceptual hash"
            ),
        ),
    ]
